/// @description Inserir descrição aqui
text02 = [
	@"CONGRATULATIONS, YOU COMPLETED THE GAME!
THANK YOU SO MUCH FOR PLAYING MY GAME.
WE APOLOGIZE IF THE GAME WAS TOO DIFFICULT IN SOME PARTS OR HAD TOO MANY BUGS.
IF THAT HAPPENED, PLEASE LEAVE SOME FEEDBACK SO WE CAN FIX IT.
THERE WILL BE MORE UPDATES TO IMPROVE THE GAME.

THANK YOU FOR PLAYING!"
]