/// @description Inserir descrição aqui
text02 = [
	@"CONGRATULATIONS, YOU COMPLETED THE GAME. THANK YOU VERY MUCH FOR PLAYING. I TRULY APPRECIATE THAT YOU PLAYED IT I PUT A LOT OF EFFORT AND CARE INTO IT. I’M SORRY IF YOU STRUGGLED WITH ANY HARD PARTS OR IF THE GAME HAD TOO MANY BUGS. I’M A BEGINNER IN THE WORLD OF GAME PROGRAMMING, BUT I WANTED TO TAKE PART IN THE EVENT. I HOPE NEXT YEAR WILL BE EVEN BETTER THAN THIS ONE.

THANK YOU FOR PLAYING MY GAME. <3"
]