/// @description Inserir descrição aqui
options = ["PLAYE", "INSTRUCTIONS", "ABOUT"]
op_max =  array_length(options);
index = 0;
screens = 0;

instructions = [
	@"USE W, A, S, D TO MOVE.
YOUR GOAL IS TO COLLECT A GREEN ORB IN EACH LEVEL WHILE ESCAPING FROM MONSTERS AND TRAPS.

THERE ARE TWO TYPES OF MONSTERS:

DEMONS: THEY CHASE YOU FOR A CERTAIN DISTANCE. DON’T GET TOO CLOSE.

SKELETONS: THEY SHOOT ARROWS FROM DIFFERENT POSITIONS AND AT DIFFERENT SPEEDS.

THERE ARE ALSO SPIKED FLOORS, WITH SPEED THAT CHANGES DEPENDING ON THE LEVEL.
THE GAME HAS 9 LEVELS IN TOTAL, AND IN SOME OF THEM YOU’LL HAVE TO MOVE THROUGH THE DARK.

NOW GO!
COLLECT THE GREEN ORBS, AVOID MONSTERS AND TRAPS, AND BEAT THE GAME.

GOOD LUCK!"
]

about = [
	@"THE GAME WAS MADE FOR LUDUM DARE 58 IN 72 HOURS.
I WAS INSPIRED BY GAMES SUCH AS DWARF FORTRESS AND PRELUDE OF THE CHAMBERED.
NONE OF THE SCENERY SPRITES WERE MADE BY ME — THE ORIGINAL CREATOR IS RGS_DEV, AND THEY WERE TAKEN FROM ITCH.IO."
]