/// @description Inserir descrição aqui
options = ["PLAYE", "INSTRUCTIONS", "CREDITS"]
op_max =  array_length(options);
index = 0;
screens = 0;

instructions = [
	@"USE W, S, A, D TO MOVE AROUND THE MAP.
	YOUR GOAL IS TO COLLECT ALL THE ORBS SCATTERED ACROSS THE AREA TO LEVEL UP.
	BUT BE VERY CAREFUL — MONSTERS ARE ALWAYS LURKING AND CAN CHASE YOU FOR A CERTAIN DISTANCE IF THEY SPOT YOU.

	IN SOME ROOMS, YOU MIGHT BARELY SEE ANYTHING, SO STAY ALERT AND MOVE CAREFULLY.
	ALSO, WATCH OUT FOR THE SPIKES ON THE FLOOR, THEY CAN DEAL A LOT OF DAMAGE IF YOU’RE NOT PAYING ATTENTION.

	GOOD LUCK, AND HAVE FUN PLAYING!"
]

credits = [
	@"NKNINININII"
]