/// @description Inserir descrição aqui
options = ["PLAYE", "INSTRUCTIONS", "ABOUT"]
op_max =  array_length(options);
index = 0;
screens = 0;

instructions = [
	@"USE W, S, A, D TO MOVE AROUND THE MAP.
	YOUR GOAL IS TO COLLECT ALL THE ORBS SCATTERED ACROSS THE AREA TO LEVEL UP.
	BUT BE VERY CAREFUL — MONSTERS ARE ALWAYS LURKING AND CAN CHASE YOU FOR A CERTAIN DISTANCE IF THEY SPOT YOU.

	IN SOME ROOMS, YOU MIGHT BARELY SEE ANYTHING, SO STAY ALERT AND MOVE CAREFULLY.
	ALSO, WATCH OUT FOR THE SPIKES ON THE FLOOR, THEY CAN DEAL A LOT OF DAMAGE IF YOU’RE NOT PAYING ATTENTION.

	GOOD LUCK, AND HAVE FUN PLAYING!"
]

about = [
	@"CREATED BY VITOR ALEXANDRINO FOR LUDUM DARE 58.

	SCENERY PIXEL ART MADE BY RGS_DEV.

	RGS_DEV PROFILE LINK: ITCH.IO/PROFILE/RGSDEV



	THE GAME WAS CREATED IN 72 HOURS FOR A COMPETITION CALLED LUDUM DARE.
	
	MADE BY A 19-YEAR-OLD BRAZILIAN FROM THE STATE OF SÃO PAULO. 
	
	INSPIRED BY TOP-DOWN RPG GAMES SUCH AS DWARF FORTRESS AND PRELUDE OF THE CHAMBERED."
]